---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  client_rb:
    data_collector.server_url: 'http://YOUR_WORKSTATION_PRIVATE_IP/data-collector/v0/'
    data_collector.token: '93a49a4f2482c64126f7b6015e6b0f30284287ee4054ff8807fb63d9cbd1c506'

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[my_apache::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
